name: CI Meson C Tests & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build gcc python3-pip gcovr lcov
          pip3 install --user meson gcovr
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Clone Unity
        run: |
          git clone --recursive https://github.com/ThrowTheSwitch/Unity.git test/Unity

      - name: Clone CMock
        run: |
          git clone --recursive https://github.com/ThrowTheSwitch/CMock.git test/CMock

      - name: Create mocks directory
        run: mkdir -p test/mocks


      - name: Patch CMock script
        run: |
          sed -i "s|require \\\"\\\#{ENV\\['CMOCK_DIR'\\]\\}/lib/cmock\\\"|require_relative '../lib/cmock'|" test/CMock/scripts/create_mock.rb


      - name: Generate all needed mocks
        run: |
          export CMOCK_DIR=$PWD/test/CMock
          export MOCK_OUT=$PWD/test/mocks
          for header in include/*.h; do
            if grep -q "MOCK_ME" "$header"; then
              ruby test/CMock/scripts/create_mock.rb "$header"
            fi
          done

      - name: Configure Meson
        run: |
            meson setup build --wipe --buildtype=debug -Db_coverage=true

      - name: Build
        run: |
          export PATH=$HOME/.local/bin:$PATH
          ninja -C build

      - name: Run tests
        run: |
          export PATH=$HOME/.local/bin:$PATH
          meson test -C build

      - name: Generate coverage report
        run: |
          export PATH=$HOME/.local/bin:$PATH
          mkdir -p build/coverage
          cd build/coverage
          gcovr -r ../.. --html --html-details --html-theme=github.blue -o coverage.html

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/coverage/